config/routes.rb
Rails.application.routes.draw do
  root to: "quizzes#index"

  resources :quizzes, only: [:show]

  namespace :admin do
    resources :quizzes do
      resources :questions, only: [:new, :create]
    end

    resources :questions, only: [:edit, :update, :destroy]
    resources :answers, only: [:edit, :update, :destroy]
    resources :hints, only: [:edit, :update, :destroy]
    resources :options, only: [:edit, :update, :destroy]
    resources :further_thoughts, only: [:edit, :update, :destroy]

    resources :questions, only: [] do
      resources :answers, only: [:new, :create]
      resources :hints, only: [:new, :create]
      resources :options, only: [:new, :create]
      resources :further_thoughts, only: [:new, :create]
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include QuestionChild
end

app/models/concerns/question_child.rb
module QuestionChild
  def self.included(base)
    base.send(:belongs_to, :question)
    base.send(:validates_presence_of, :question_id)
  end

  def quiz
    question.quiz
  end
end

app/models/further_thought.rb
class FurtherThought < ActiveRecord::Base
  include QuestionChild
end

app/models/hint.rb
class Hint < ActiveRecord::Base
  include QuestionChild
end

app/models/option.rb
class Option < ActiveRecord::Base
  include QuestionChild
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz
  has_many :options
  has_many :hints
  has_many :answers
  has_many :further_thoughts
  validates_presence_of :quiz_id

  def resources
    options + hints + answers + further_thoughts
  end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :questions
  validates_uniqueness_of :slug
  def to_param
    slug
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::QuestionResourcesController
  def resource
    Answer
  end
end

app/controllers/admin/hints_controller.rb
class Admin::HintsController < Admin::QuestionResourcesController
  def resource
    Hint
  end
end

app/controllers/admin/options_controller.rb
class Admin::OptionsController < Admin::QuestionResourcesController
  def resource
    Option
  end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  def index
    @quizzes = Quiz.all
  end

  def show
  end

  def new
    @quiz = Quiz.new
  end

  def edit
  end

  def create
    @quiz = Quiz.new(quiz_params)

    if @quiz.save
      redirect_to admin_quiz_path(@quiz), notice: 'Quiz was successfully created.'
    else
      render :new
    end
  end

  def update
    if @quiz.update(quiz_params)
      redirect_to admin_quiz_path(@quiz), notice: 'Quiz was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @quiz.destroy
    redirect_to admin_quizzes_path, notice: 'Quiz was successfully destroyed.'
  end

  private
    def set_quiz
      @quiz = Quiz.find_by(slug: params[:id])
      raise ActiveRecord::RecordNotFound unless @quiz
    end

    def quiz_params
      params.require(:quiz).permit(:title, :slug)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/question_resources_controller.rb
class QuestionResourcesController < ApplicationController
  include QuestionNested
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def new
    @resource = resource.new(question: @question)
    render :template => "question_resources/new"
  end

  def edit
    render :template => "question_resources/edit"
  end

  def create
    @resource = resource.new(resource_params.merge({question: @question}))

    if @resource.save
      redirect_to quiz_path(@resource.quiz), notice: "#{resource.class.name} was successfully created."
    else
      render :template => "question_resources/new"
    end
  end

  def update
    if @resource.update(resource_params)
      redirect_to quiz_path(@resource.quiz), notice: "#{resource.class.name} was successfully updated."
    else
      render :template => "question_resources/edit"
    end
  end

  # DELETE /further_thoughts/1
  def destroy
    @resource.destroy
    redirect_to quiz_path(@resource.quiz), notice: "#{resource.class.name} was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = resource.find(params[:id])
    end

    def resource
      raise "Abstract -- return class that this controller manages"
    end

    # Only allow a trusted parameter "white list" through.
    def resource_params
      params.require(resource.name.underscore).permit(:body)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_quiz, only: [:new, :create]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def new
    @question = Question.new(:quiz => @quiz)
  end

  def edit
  end

  def create
    @question = Question.new(question_params.merge(:quiz => @quiz))

    if @question.save
      redirect_to quiz_path(@quiz), notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to quiz_url(@question.quiz), notice: 'Question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_quiz
      @quiz = Quiz.find(params[:quiz_id])
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:body, :quiz_id)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz

  def show
  end

  def set_quiz
    @quiz = Quiz.find_by(slug: params[:id])
    raise ActiveRecord::RecordNotFound unless @quiz
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/further_thoughts_helper.rb
module FurtherThoughtsHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_controller_helper.rb
module QuestionsControllerHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/admin/quizzes/_form.html.erb
<%= form_for([:admin, @quiz]) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_quiz_path(@quiz) %> |
<%= link_to 'Back', admin_quizzes_path %>

app/views/admin/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.title %></td>
        <td><%= quiz.slug %></td>
        <td><%= link_to 'View Quiz', quiz_path(quiz) %></td>
        <td><%= link_to 'Admin View', admin_quiz_path(quiz) %></td>
        <td><%= link_to 'Edit', edit_admin_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_admin_quiz_path %>

app/views/admin/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_quizzes_path %>

app/views/admin/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Quiz: <%= @quiz.title %></h3>

<p>
  <strong>Slug:</strong>
  <%= @quiz.slug %>
</p>

<h3>Questions</h3>
<ul>
  <% @quiz.questions.each do |q| %>
    <li>
      <p>
        <span><strong>Question: </strong><%= q.body %></span>
        <span><%= link_to "edit", edit_admin_question_path(q) %></span>
        <span><%= link_to "delete", admin_question_path(q), method: :delete %></span>
      </p>
      <% ["option", "hint", "answer", "further_thought"].each do |resource| %>
        <% res = q.send(resource.pluralize) %>
        <% if res.any? %>
          <% res.each do |r| %>
            <p>
              <strong><%=resource.capitalize%>:</strong> <%= r.body %>
              <span><%= link_to "edit", send("edit_admin_#{resource}_path", r) %></span>
              <span><%= link_to "delete", send("admin_#{resource}_path", r), method: :delete %></span>
            </p>
          <% end %>
        <% end %>
        <p><%= link_to "add #{resource}", send("new_admin_question_#{resource}_path", q) %></p>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'View Quiz', quiz_path(@quiz) %> |
<%= link_to 'Edit', edit_admin_quiz_path(@quiz) %> |
<%= link_to 'Add Question', new_admin_quiz_question_path(@quiz) %> |
<%= link_to 'Back', admin_quizzes_path %>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/show.html.erb
<div class="container">
  <h1>Quiz!</h1>
  <h2><%= @quiz.title %></h2>


  <h3>Explanation</h3>
  <p>Go through the questions below. The purpose is not to test you, it's to allow you to test yourself.</p>
  <p>Your goal isn't to get the answers right, it's to assimilate the knowledge in the questions.</p>
  <p>This is self-scored, it is for you to help push yourself along and address gaps in your knowledge.</p>

  <h3>How to take the quiz</h3>
  <ol>
    <li>Look at the question, answer it in your head.</li>
    <li>If you need help, click the "hint" option.</li>
    <li>If you don't know the answer, go ahead and look at it, and then read through the further thought to help you understand why that is the answer.</li>
    <li>If you do know the answer, say it to yourself in your head, then look and see that you were correct.</li>
    <li>Go ahead and read the "further thought" to see some of the context and nuance behind the answers that we were thinking about as we wrote them.</li>
  </ol>


  <% @quiz.questions.each do |question| %>
    <div class="question">
      <h3>Q: <%= question.body %></h3>
      <div class="body">
        <% if question.options.any? %>
          <div class="options">
            <% question.options.order(id: :asc).each do |option| %>
              <div class='option'>
                <div class='value'><%= option.body %></div>
              </div>
            <% end %>
          </div>
        <% end %>

        <% if question.hints.any? %>
          <% question.hints.each do |hint| %>
            <div class="hint"><%= hint.body %></div>
          <% end %>
        <% end %>

        <% if question.answers.any? %>
          <% question.answers.each do |answer| %>
            <div class="answer"><b><%= answer.body %></b></div>
          <% end %>
        <% end %>

        <% if question.further_thoughts.any? %>
          <% question.further_thoughts.each do |further_thought| %>
            <div class="further-thought"><b><%= further_thought.body %></b></div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>